// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="lossless_doscanline,hls_ip_2018_2_1,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7vx485tffg1158-2,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.900000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=8,HLS_SYN_FF=4400,HLS_SYN_LUT=9405,HLS_VERSION=2018_2_1}" *)

module lossless_doscanline (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        psl_address0,
        psl_ce0,
        psl_q0,
        psl_address1,
        psl_ce1,
        psl_q1,
        sl_address0,
        sl_ce0,
        sl_we0,
        sl_d0,
        sl_q0,
        no,
        color,
        bpp16,
        vLUT_address0,
        vLUT_ce0,
        vLUT_q0,
        vLUT_address1,
        vLUT_ce1,
        vLUT_q1,
        limit_reduce_i,
        limit_reduce_o,
        limit_reduce_o_ap_vld,
        N_address0,
        N_ce0,
        N_we0,
        N_d0,
        N_q0,
        A_address0,
        A_ce0,
        A_we0,
        A_d0,
        A_q0,
        alpha,
        ceil_half_alpha,
        B_address0,
        B_ce0,
        B_we0,
        B_d0,
        B_q0,
        RESET,
        limit,
        qbpp,
        classmap_address0,
        classmap_ce0,
        classmap_q0,
        C_address0,
        C_ce0,
        C_we0,
        C_d0,
        C_q0,
        highmask
);

parameter    ap_ST_fsm_state1 = 36'd1;
parameter    ap_ST_fsm_state2 = 36'd2;
parameter    ap_ST_fsm_state3 = 36'd4;
parameter    ap_ST_fsm_state4 = 36'd8;
parameter    ap_ST_fsm_state5 = 36'd16;
parameter    ap_ST_fsm_state6 = 36'd32;
parameter    ap_ST_fsm_state7 = 36'd64;
parameter    ap_ST_fsm_state8 = 36'd128;
parameter    ap_ST_fsm_state9 = 36'd256;
parameter    ap_ST_fsm_state10 = 36'd512;
parameter    ap_ST_fsm_state11 = 36'd1024;
parameter    ap_ST_fsm_state12 = 36'd2048;
parameter    ap_ST_fsm_state13 = 36'd4096;
parameter    ap_ST_fsm_state14 = 36'd8192;
parameter    ap_ST_fsm_state15 = 36'd16384;
parameter    ap_ST_fsm_state16 = 36'd32768;
parameter    ap_ST_fsm_state17 = 36'd65536;
parameter    ap_ST_fsm_state18 = 36'd131072;
parameter    ap_ST_fsm_state19 = 36'd262144;
parameter    ap_ST_fsm_state20 = 36'd524288;
parameter    ap_ST_fsm_state21 = 36'd1048576;
parameter    ap_ST_fsm_state22 = 36'd2097152;
parameter    ap_ST_fsm_state23 = 36'd4194304;
parameter    ap_ST_fsm_state24 = 36'd8388608;
parameter    ap_ST_fsm_state25 = 36'd16777216;
parameter    ap_ST_fsm_state26 = 36'd33554432;
parameter    ap_ST_fsm_state27 = 36'd67108864;
parameter    ap_ST_fsm_state28 = 36'd134217728;
parameter    ap_ST_fsm_state29 = 36'd268435456;
parameter    ap_ST_fsm_state30 = 36'd536870912;
parameter    ap_ST_fsm_state31 = 36'd1073741824;
parameter    ap_ST_fsm_state32 = 36'd2147483648;
parameter    ap_ST_fsm_state33 = 36'd4294967296;
parameter    ap_ST_fsm_state34 = 36'd8589934592;
parameter    ap_ST_fsm_state35 = 36'd17179869184;
parameter    ap_ST_fsm_state36 = 36'd34359738368;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [12:0] psl_address0;
output   psl_ce0;
input  [15:0] psl_q0;
output  [12:0] psl_address1;
output   psl_ce1;
input  [15:0] psl_q1;
output  [12:0] sl_address0;
output   sl_ce0;
output   sl_we0;
output  [15:0] sl_d0;
input  [15:0] sl_q0;
input  [31:0] no;
input  [31:0] color;
input  [31:0] bpp16;
output  [14:0] vLUT_address0;
output   vLUT_ce0;
input  [31:0] vLUT_q0;
output  [14:0] vLUT_address1;
output   vLUT_ce1;
input  [31:0] vLUT_q1;
input  [31:0] limit_reduce_i;
output  [31:0] limit_reduce_o;
output   limit_reduce_o_ap_vld;
output  [8:0] N_address0;
output   N_ce0;
output   N_we0;
output  [31:0] N_d0;
input  [31:0] N_q0;
output  [8:0] A_address0;
output   A_ce0;
output   A_we0;
output  [31:0] A_d0;
input  [31:0] A_q0;
input  [31:0] alpha;
input  [31:0] ceil_half_alpha;
output  [8:0] B_address0;
output   B_ce0;
output   B_we0;
output  [31:0] B_d0;
input  [31:0] B_q0;
input  [31:0] RESET;
input  [31:0] limit;
input  [31:0] qbpp;
output  [9:0] classmap_address0;
output   classmap_ce0;
input  [31:0] classmap_q0;
output  [8:0] C_address0;
output   C_ce0;
output   C_we0;
output  [31:0] C_d0;
input  [31:0] C_q0;
input  [31:0] highmask;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[12:0] psl_address0;
reg psl_ce0;
reg[12:0] psl_address1;
reg psl_ce1;
reg[12:0] sl_address0;
reg sl_ce0;
reg sl_we0;
reg[15:0] sl_d0;
reg[14:0] vLUT_address0;
reg vLUT_ce0;
reg[14:0] vLUT_address1;
reg vLUT_ce1;
reg[31:0] limit_reduce_o;
reg limit_reduce_o_ap_vld;
reg[8:0] N_address0;
reg N_ce0;
reg N_we0;
reg[31:0] N_d0;
reg[8:0] A_address0;
reg A_ce0;
reg A_we0;
reg[31:0] A_d0;
reg[8:0] B_address0;
reg B_ce0;
reg B_we0;
reg[31:0] B_d0;
reg[9:0] classmap_address0;
reg classmap_ce0;
reg C_ce0;
reg C_we0;

(* fsm_encoding = "none" *) reg   [35:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] bits;
reg   [31:0] reg_r;
wire   [31:0] grp_fu_813_p3;
reg   [31:0] reg_843;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state25;
wire   [1:0] grp_fu_829_p3;
reg   [1:0] reg_848;
wire    ap_CS_fsm_state2;
wire   [0:0] tmp_fu_857_p2;
reg   [0:0] tmp_reg_1583;
wire    ap_CS_fsm_state3;
reg   [15:0] Rd_1_reg_1610;
wire    ap_CS_fsm_state4;
wire   [16:0] tmp_182_cast_fu_874_p1;
reg   [16:0] tmp_182_cast_reg_1617;
wire   [16:0] tmp_195_cast_fu_878_p1;
reg   [16:0] tmp_195_cast_reg_1622;
reg   [0:0] tmp_166_reg_1627;
wire   [0:0] tmp_167_fu_900_p2;
reg   [0:0] tmp_167_reg_1634;
wire   [0:0] tmp_168_fu_906_p2;
reg   [0:0] tmp_168_reg_1640;
reg   [0:0] tmp_160_reg_1650;
wire    ap_CS_fsm_state5;
wire   [0:0] tmp_161_fu_943_p2;
reg   [0:0] tmp_161_reg_1657;
wire   [0:0] tmp_162_fu_949_p2;
reg   [0:0] tmp_162_reg_1663;
wire   [31:0] newSel5_fu_1016_p3;
reg   [31:0] newSel5_reg_1673;
reg   [0:0] tmp_170_reg_1678;
wire   [0:0] tmp_171_fu_1045_p2;
reg   [0:0] tmp_171_reg_1685;
wire   [0:0] tmp_172_fu_1051_p2;
reg   [0:0] tmp_172_reg_1691;
wire    ap_CS_fsm_state6;
wire   [31:0] newSel2_fu_1119_p3;
reg   [31:0] newSel2_reg_1706;
wire   [31:0] newSel8_fu_1173_p3;
reg   [31:0] newSel8_reg_1711;
reg   [15:0] Ix_1_reg_1716;
wire    ap_CS_fsm_state7;
wire   [0:0] tmp_173_fu_1190_p2;
reg   [0:0] tmp_173_reg_1723;
wire   [0:0] grp_fu_793_p2;
reg   [0:0] tmp_183_reg_1732;
wire   [15:0] Px_3_fu_1261_p3;
reg   [15:0] Px_3_reg_1736;
wire  signed [31:0] i_10_fu_1269_p2;
reg  signed [31:0] i_10_reg_1741;
wire    ap_CS_fsm_state11;
wire   [0:0] tmp_193_fu_1275_p2;
reg   [0:0] tmp_193_reg_1747;
wire  signed [63:0] tmp_196_fu_1280_p1;
reg  signed [63:0] tmp_196_reg_1751;
reg   [15:0] Ix_3_reg_1761;
wire    ap_CS_fsm_state12;
wire   [31:0] phitmp_fu_1285_p2;
wire    ap_CS_fsm_state13;
wire   [0:0] tmp_203_fu_1302_p2;
reg   [0:0] tmp_203_reg_1794;
wire    ap_CS_fsm_state15;
wire    grp_process_run_fu_766_ap_idle;
wire    grp_process_run_fu_766_ap_ready;
wire    grp_process_run_fu_766_ap_done;
wire   [31:0] i_11_fu_1313_p2;
wire    ap_CS_fsm_state18;
wire    grp_lossless_end_of_run_fu_730_ap_idle;
wire    grp_lossless_end_of_run_fu_730_ap_ready;
wire    grp_lossless_end_of_run_fu_730_ap_done;
reg   [0:0] tmp_156_reg_1875;
reg   [0:0] tmp_174_reg_1884;
reg   [0:0] tmp_189_reg_1899;
reg    ap_predicate_op208_call_state18;
reg    ap_block_state18_on_subcall_done;
wire   [31:0] i_9_fu_1329_p2;
wire    ap_CS_fsm_state20;
wire   [15:0] tmp_152_fu_1351_p2;
reg   [15:0] tmp_152_reg_1820;
reg   [15:0] Rd_reg_1825;
wire    ap_CS_fsm_state21;
wire   [15:0] tmp_154_fu_1373_p2;
reg   [15:0] tmp_154_reg_1837;
wire    ap_CS_fsm_state22;
reg   [31:0] vLUT_load_1_reg_1847;
wire    ap_CS_fsm_state23;
wire  signed [31:0] cont_fu_1434_p2;
reg  signed [31:0] cont_reg_1862;
reg   [15:0] Ix_reg_1868;
wire    ap_CS_fsm_state24;
wire   [0:0] tmp_156_fu_1439_p2;
wire   [0:0] grp_fu_837_p2;
wire   [15:0] Px_1_fu_1508_p3;
reg   [15:0] Px_1_reg_1888;
wire  signed [31:0] i_8_fu_1516_p2;
reg  signed [31:0] i_8_reg_1893;
wire    ap_CS_fsm_state28;
wire   [0:0] tmp_189_fu_1522_p2;
wire  signed [63:0] tmp_194_fu_1527_p1;
reg  signed [63:0] tmp_194_reg_1903;
reg   [15:0] Ix_2_reg_1913;
wire    ap_CS_fsm_state29;
wire   [31:0] phitmp2_fu_1532_p2;
wire    ap_CS_fsm_state30;
wire    ap_CS_fsm_state31;
wire   [0:0] tmp_202_fu_1549_p2;
reg   [0:0] tmp_202_reg_1946;
wire    ap_CS_fsm_state33;
wire    grp_lossless_regular_mod_fu_698_ap_start;
wire    grp_lossless_regular_mod_fu_698_ap_done;
wire    grp_lossless_regular_mod_fu_698_ap_idle;
wire    grp_lossless_regular_mod_fu_698_ap_ready;
reg   [15:0] grp_lossless_regular_mod_fu_698_Px;
reg   [15:0] grp_lossless_regular_mod_fu_698_xp_read;
wire   [8:0] grp_lossless_regular_mod_fu_698_N_address0;
wire    grp_lossless_regular_mod_fu_698_N_ce0;
wire    grp_lossless_regular_mod_fu_698_N_we0;
wire   [31:0] grp_lossless_regular_mod_fu_698_N_d0;
wire   [8:0] grp_lossless_regular_mod_fu_698_A_address0;
wire    grp_lossless_regular_mod_fu_698_A_ce0;
wire    grp_lossless_regular_mod_fu_698_A_we0;
wire   [31:0] grp_lossless_regular_mod_fu_698_A_d0;
wire   [8:0] grp_lossless_regular_mod_fu_698_C_address0;
wire    grp_lossless_regular_mod_fu_698_C_ce0;
wire    grp_lossless_regular_mod_fu_698_C_we0;
wire   [31:0] grp_lossless_regular_mod_fu_698_C_d0;
wire   [8:0] grp_lossless_regular_mod_fu_698_B_address0;
wire    grp_lossless_regular_mod_fu_698_B_ce0;
wire    grp_lossless_regular_mod_fu_698_B_we0;
wire   [31:0] grp_lossless_regular_mod_fu_698_B_d0;
wire   [31:0] grp_lossless_regular_mod_fu_698_bits_o;
wire    grp_lossless_regular_mod_fu_698_bits_o_ap_vld;
wire   [31:0] grp_lossless_regular_mod_fu_698_reg_r_o;
wire    grp_lossless_regular_mod_fu_698_reg_r_o_ap_vld;
wire    grp_lossless_end_of_run_fu_730_ap_start;
reg   [15:0] grp_lossless_end_of_run_fu_730_Ra;
reg   [15:0] grp_lossless_end_of_run_fu_730_Rb;
reg   [15:0] grp_lossless_end_of_run_fu_730_Ix;
reg   [0:0] grp_lossless_end_of_run_fu_730_RItype;
wire   [8:0] grp_lossless_end_of_run_fu_730_N_address0;
wire    grp_lossless_end_of_run_fu_730_N_ce0;
wire    grp_lossless_end_of_run_fu_730_N_we0;
wire   [31:0] grp_lossless_end_of_run_fu_730_N_d0;
wire   [8:0] grp_lossless_end_of_run_fu_730_A_address0;
wire    grp_lossless_end_of_run_fu_730_A_ce0;
wire    grp_lossless_end_of_run_fu_730_A_we0;
wire   [31:0] grp_lossless_end_of_run_fu_730_A_d0;
wire   [8:0] grp_lossless_end_of_run_fu_730_B_address0;
wire    grp_lossless_end_of_run_fu_730_B_ce0;
wire    grp_lossless_end_of_run_fu_730_B_we0;
wire   [31:0] grp_lossless_end_of_run_fu_730_B_d0;
wire   [31:0] grp_lossless_end_of_run_fu_730_bits_o;
wire    grp_lossless_end_of_run_fu_730_bits_o_ap_vld;
wire   [31:0] grp_lossless_end_of_run_fu_730_reg_r_o;
wire    grp_lossless_end_of_run_fu_730_reg_r_o_ap_vld;
wire    grp_process_run_fu_766_ap_start;
reg   [31:0] grp_process_run_fu_766_runlen;
reg   [0:0] grp_process_run_fu_766_eoline;
wire   [31:0] grp_process_run_fu_766_bits_o;
wire    grp_process_run_fu_766_bits_o_ap_vld;
wire   [31:0] grp_process_run_fu_766_reg_r_o;
wire    grp_process_run_fu_766_reg_r_o_ap_vld;
wire   [31:0] grp_process_run_fu_766_limit_reduce;
wire    grp_process_run_fu_766_limit_reduce_ap_vld;
reg  signed [31:0] i_4_reg_361;
wire   [0:0] tmp_207_fu_1319_p2;
reg   [15:0] Rc_1_reg_373;
reg   [15:0] maxx_reg_383;
reg   [15:0] minx_5_reg_393;
reg   [31:0] i_5_reg_403;
reg   [31:0] RUNcnt_2_reg_414;
reg   [31:0] RUNcnt1_1_reg_426;
reg   [15:0] Rb_4_reg_439;
reg   [15:0] Ix_s_reg_450;
reg   [15:0] Rd_2_reg_460;
reg   [31:0] i_6_reg_470;
reg   [15:0] Ra_2_reg_481;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state10;
reg   [15:0] Rb_6_reg_494;
reg   [15:0] Rc_3_reg_506;
reg  signed [31:0] i_7_reg_519;
reg   [15:0] Rd6_reg_530;
reg   [15:0] Ix3_reg_650;
reg   [15:0] ap_phi_mux_Ra_1_phi_fu_542_p4;
reg   [15:0] Ra_1_reg_539;
wire    ap_CS_fsm_state27;
reg   [15:0] ap_phi_mux_Rb_3_phi_fu_553_p4;
reg   [15:0] Rb_3_reg_550;
reg   [15:0] Rb_1_reg_686;
reg   [15:0] ap_phi_mux_Rc_2_phi_fu_564_p4;
reg   [15:0] Rc_2_reg_561;
reg   [15:0] maxx_5_reg_604;
reg   [31:0] i_2_reg_674;
reg  signed [31:0] ap_phi_mux_i_3_phi_fu_574_p4;
reg  signed [31:0] i_3_reg_571;
reg  signed [31:0] i_reg_591;
reg   [15:0] Rc3_reg_580;
wire   [0:0] tmp_205_fu_1335_p2;
reg   [15:0] minx_reg_616;
reg   [31:0] RUNcnt_reg_627;
reg   [31:0] i_1_reg_639;
reg   [31:0] RUNcnt_1_reg_661;
reg    grp_lossless_regular_mod_fu_698_ap_start_reg;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state26;
reg    grp_lossless_end_of_run_fu_730_ap_start_reg;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state34;
reg    grp_process_run_fu_766_ap_start_reg;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state32;
wire    ap_CS_fsm_state35;
wire    ap_CS_fsm_state19;
wire    ap_CS_fsm_state36;
wire  signed [63:0] tmp_159_fu_869_p1;
wire  signed [63:0] tmp_25_cast_fu_918_p1;
wire   [63:0] tmp_164_fu_965_p1;
wire  signed [63:0] tmp_26_cast_fu_1063_p1;
wire  signed [63:0] tmp_157_fu_1068_p1;
wire  signed [63:0] tmp_188_fu_1196_p1;
wire  signed [63:0] tmp_201_fu_1297_p1;
wire  signed [63:0] tmp_206_fu_1308_p1;
wire  signed [63:0] tmp_204_fu_1324_p1;
wire  signed [63:0] tmp_148_fu_1346_p1;
wire  signed [63:0] tmp_22_cast_fu_1368_p1;
wire  signed [63:0] tmp_151_fu_1402_p1;
wire  signed [63:0] tmp_24_cast_fu_1418_p1;
wire  signed [63:0] tmp_s_fu_1423_p1;
wire  signed [63:0] tmp_179_fu_1444_p1;
wire  signed [63:0] tmp_199_fu_1544_p1;
wire   [0:0] grp_fu_799_p3;
wire   [31:0] grp_fu_807_p2;
wire   [0:0] grp_fu_821_p3;
wire   [31:0] tmp_158_fu_863_p2;
wire   [16:0] diff_1_fu_882_p2;
wire   [15:0] tmp_165_fu_888_p1;
wire   [15:0] tmp_25_fu_912_p2;
wire   [16:0] tmp_181_cast_fu_923_p1;
wire  signed [16:0] diff_fu_926_p2;
wire  signed [17:0] diff_cast_fu_931_p1;
wire   [17:0] tmp_163_fu_955_p2;
wire  signed [31:0] tmp_191_cast_fu_961_p1;
wire   [0:0] sel_tmp5_fu_974_p2;
wire   [0:0] sel_tmp1_fu_984_p2;
wire   [0:0] sel_tmp10_fu_989_p2;
wire   [0:0] sel_tmp8_fu_979_p2;
wire   [0:0] sel_tmp3_fu_970_p2;
wire   [0:0] or_cond1_fu_1002_p2;
wire   [31:0] newSel3_fu_994_p3;
wire   [31:0] newSel4_fu_1008_p3;
wire   [16:0] tmp_212_cast_fu_1024_p1;
wire   [16:0] diff_2_fu_1028_p2;
wire   [15:0] tmp_169_fu_1033_p1;
wire   [15:0] tmp_26_fu_1057_p2;
wire   [0:0] sel_tmp6_fu_1077_p2;
wire   [0:0] sel_tmp9_fu_1087_p2;
wire   [0:0] sel_tmp2_fu_1092_p2;
wire   [0:0] sel_tmp7_fu_1082_p2;
wire   [0:0] sel_tmp4_fu_1073_p2;
wire   [0:0] or_cond_fu_1105_p2;
wire   [31:0] newSel_fu_1097_p3;
wire   [31:0] newSel1_fu_1111_p3;
wire   [0:0] sel_tmp12_fu_1131_p2;
wire   [0:0] sel_tmp14_fu_1141_p2;
wire   [0:0] sel_tmp15_fu_1146_p2;
wire   [0:0] sel_tmp13_fu_1136_p2;
wire   [0:0] sel_tmp11_fu_1127_p2;
wire   [0:0] or_cond2_fu_1159_p2;
wire   [31:0] newSel6_fu_1151_p3;
wire   [31:0] newSel7_fu_1165_p3;
wire   [31:0] tmp5_fu_1181_p2;
wire  signed [31:0] cont_1_fu_1185_p2;
wire   [0:0] tmp_184_fu_1201_p2;
wire   [15:0] Px_13_fu_1215_p3;
wire   [15:0] Px_12_fu_1207_p3;
wire   [15:0] tmp_187_fu_1235_p2;
wire   [0:0] tmp_185_fu_1223_p2;
wire   [0:0] tmp_186_fu_1229_p2;
wire   [0:0] sel_tmp16_fu_1247_p2;
wire   [15:0] Px_5_fu_1241_p2;
wire   [15:0] Px_9_fu_1253_p3;
wire   [31:0] tmp_200_fu_1291_p2;
wire   [31:0] tmp_147_fu_1340_p2;
wire   [15:0] tmp_153_fu_1357_p2;
wire   [15:0] tmp_22_fu_1362_p2;
wire   [16:0] tmp_164_cast_fu_1382_p1;
wire   [16:0] tmp_149_fu_1386_p2;
wire  signed [17:0] tmp_165_cast_fu_1392_p1;
wire   [17:0] tmp_163_cast_fu_1379_p1;
wire   [17:0] tmp_150_fu_1396_p2;
wire   [15:0] tmp_155_fu_1407_p2;
wire   [15:0] tmp_24_fu_1412_p2;
wire   [31:0] tmp4_fu_1428_p2;
wire   [0:0] tmp_175_fu_1448_p2;
wire   [15:0] Px_10_fu_1454_p3;
wire   [15:0] Px_11_fu_1462_p3;
wire   [15:0] tmp_178_fu_1482_p2;
wire   [0:0] tmp_176_fu_1470_p2;
wire   [0:0] tmp_177_fu_1476_p2;
wire   [0:0] sel_tmp_fu_1494_p2;
wire   [15:0] Px_fu_1488_p2;
wire   [15:0] Px_6_fu_1500_p3;
wire   [31:0] tmp_198_fu_1538_p2;
reg   [35:0] ap_NS_fsm;
reg    ap_condition_339;
reg    ap_condition_348;

// power-on initialization
initial begin
#0 ap_CS_fsm = 36'd1;
#0 bits = 32'd0;
#0 reg_r = 32'd0;
#0 grp_lossless_regular_mod_fu_698_ap_start_reg = 1'b0;
#0 grp_lossless_end_of_run_fu_730_ap_start_reg = 1'b0;
#0 grp_process_run_fu_766_ap_start_reg = 1'b0;
end

lossless_regular_mod grp_lossless_regular_mod_fu_698(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_lossless_regular_mod_fu_698_ap_start),
    .ap_done(grp_lossless_regular_mod_fu_698_ap_done),
    .ap_idle(grp_lossless_regular_mod_fu_698_ap_idle),
    .ap_ready(grp_lossless_regular_mod_fu_698_ap_ready),
    .Q(reg_843),
    .SIGN(reg_848),
    .Px(grp_lossless_regular_mod_fu_698_Px),
    .xp_read(grp_lossless_regular_mod_fu_698_xp_read),
    .N_address0(grp_lossless_regular_mod_fu_698_N_address0),
    .N_ce0(grp_lossless_regular_mod_fu_698_N_ce0),
    .N_we0(grp_lossless_regular_mod_fu_698_N_we0),
    .N_d0(grp_lossless_regular_mod_fu_698_N_d0),
    .N_q0(N_q0),
    .A_address0(grp_lossless_regular_mod_fu_698_A_address0),
    .A_ce0(grp_lossless_regular_mod_fu_698_A_ce0),
    .A_we0(grp_lossless_regular_mod_fu_698_A_we0),
    .A_d0(grp_lossless_regular_mod_fu_698_A_d0),
    .A_q0(A_q0),
    .C_address0(grp_lossless_regular_mod_fu_698_C_address0),
    .C_ce0(grp_lossless_regular_mod_fu_698_C_ce0),
    .C_we0(grp_lossless_regular_mod_fu_698_C_we0),
    .C_d0(grp_lossless_regular_mod_fu_698_C_d0),
    .C_q0(C_q0),
    .highmask(highmask),
    .alpha(alpha),
    .B_address0(grp_lossless_regular_mod_fu_698_B_address0),
    .B_ce0(grp_lossless_regular_mod_fu_698_B_ce0),
    .B_we0(grp_lossless_regular_mod_fu_698_B_we0),
    .B_d0(grp_lossless_regular_mod_fu_698_B_d0),
    .B_q0(B_q0),
    .ceil_half_alpha(ceil_half_alpha),
    .RESET(RESET),
    .limit(limit),
    .bits_i(bits),
    .bits_o(grp_lossless_regular_mod_fu_698_bits_o),
    .bits_o_ap_vld(grp_lossless_regular_mod_fu_698_bits_o_ap_vld),
    .reg_r_i(reg_r),
    .reg_r_o(grp_lossless_regular_mod_fu_698_reg_r_o),
    .reg_r_o_ap_vld(grp_lossless_regular_mod_fu_698_reg_r_o_ap_vld),
    .qbpp(qbpp)
);

lossless_end_of_run grp_lossless_end_of_run_fu_730(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_lossless_end_of_run_fu_730_ap_start),
    .ap_done(grp_lossless_end_of_run_fu_730_ap_done),
    .ap_idle(grp_lossless_end_of_run_fu_730_ap_idle),
    .ap_ready(grp_lossless_end_of_run_fu_730_ap_ready),
    .Ra(grp_lossless_end_of_run_fu_730_Ra),
    .Rb(grp_lossless_end_of_run_fu_730_Rb),
    .Ix(grp_lossless_end_of_run_fu_730_Ix),
    .RItype(grp_lossless_end_of_run_fu_730_RItype),
    .N_address0(grp_lossless_end_of_run_fu_730_N_address0),
    .N_ce0(grp_lossless_end_of_run_fu_730_N_ce0),
    .N_we0(grp_lossless_end_of_run_fu_730_N_we0),
    .N_d0(grp_lossless_end_of_run_fu_730_N_d0),
    .N_q0(N_q0),
    .A_address0(grp_lossless_end_of_run_fu_730_A_address0),
    .A_ce0(grp_lossless_end_of_run_fu_730_A_ce0),
    .A_we0(grp_lossless_end_of_run_fu_730_A_we0),
    .A_d0(grp_lossless_end_of_run_fu_730_A_d0),
    .A_q0(A_q0),
    .alpha(alpha),
    .ceil_half_alpha(ceil_half_alpha),
    .B_address0(grp_lossless_end_of_run_fu_730_B_address0),
    .B_ce0(grp_lossless_end_of_run_fu_730_B_ce0),
    .B_we0(grp_lossless_end_of_run_fu_730_B_we0),
    .B_d0(grp_lossless_end_of_run_fu_730_B_d0),
    .B_q0(B_q0),
    .RESET(RESET),
    .limit(limit),
    .limit_reduce(limit_reduce_i),
    .bits_i(bits),
    .bits_o(grp_lossless_end_of_run_fu_730_bits_o),
    .bits_o_ap_vld(grp_lossless_end_of_run_fu_730_bits_o_ap_vld),
    .reg_r_i(reg_r),
    .reg_r_o(grp_lossless_end_of_run_fu_730_reg_r_o),
    .reg_r_o_ap_vld(grp_lossless_end_of_run_fu_730_reg_r_o_ap_vld),
    .qbpp(qbpp)
);

process_run grp_process_run_fu_766(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_process_run_fu_766_ap_start),
    .ap_done(grp_process_run_fu_766_ap_done),
    .ap_idle(grp_process_run_fu_766_ap_idle),
    .ap_ready(grp_process_run_fu_766_ap_ready),
    .runlen(grp_process_run_fu_766_runlen),
    .eoline(grp_process_run_fu_766_eoline),
    .color(color),
    .bits_i(bits),
    .bits_o(grp_process_run_fu_766_bits_o),
    .bits_o_ap_vld(grp_process_run_fu_766_bits_o_ap_vld),
    .reg_r_i(reg_r),
    .reg_r_o(grp_process_run_fu_766_reg_r_o),
    .reg_r_o_ap_vld(grp_process_run_fu_766_reg_r_o_ap_vld),
    .limit_reduce(grp_process_run_fu_766_limit_reduce),
    .limit_reduce_ap_vld(grp_process_run_fu_766_limit_reduce_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_lossless_end_of_run_fu_730_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state16))) begin
            grp_lossless_end_of_run_fu_730_ap_start_reg <= 1'b1;
        end else if ((grp_lossless_end_of_run_fu_730_ap_ready == 1'b1)) begin
            grp_lossless_end_of_run_fu_730_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_lossless_regular_mod_fu_698_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state9))) begin
            grp_lossless_regular_mod_fu_698_ap_start_reg <= 1'b1;
        end else if ((grp_lossless_regular_mod_fu_698_ap_ready == 1'b1)) begin
            grp_lossless_regular_mod_fu_698_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_process_run_fu_766_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state14) | ((tmp_193_fu_1275_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state11)))) begin
            grp_process_run_fu_766_ap_start_reg <= 1'b1;
        end else if ((grp_process_run_fu_766_ap_ready == 1'b1)) begin
            grp_process_run_fu_766_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_156_fu_1439_p2 == 1'd1) & (grp_fu_837_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state24))) begin
        Ix3_reg_650 <= sl_q0;
    end else if ((1'b1 == ap_CS_fsm_state31)) begin
        Ix3_reg_650 <= Ix_2_reg_1913;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fu_793_p2 == 1'd0) & (tmp_173_fu_1190_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        Ix_s_reg_450 <= sl_q0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        Ix_s_reg_450 <= Ix_3_reg_1761;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fu_793_p2 == 1'd0) & (tmp_173_fu_1190_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        RUNcnt1_1_reg_426 <= 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        RUNcnt1_1_reg_426 <= RUNcnt_2_reg_414;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_156_fu_1439_p2 == 1'd1) & (grp_fu_837_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state24))) begin
        RUNcnt_1_reg_661 <= 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state31)) begin
        RUNcnt_1_reg_661 <= RUNcnt_reg_627;
    end
end

always @ (posedge ap_clk) begin
    if ((grp_fu_793_p2 == 1'd1)) begin
        if (((tmp_173_fu_1190_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
            RUNcnt_2_reg_414 <= 32'd1;
        end else if ((1'b1 == ap_CS_fsm_state12)) begin
            RUNcnt_2_reg_414 <= phitmp_fu_1285_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((grp_fu_837_p2 == 1'd1)) begin
        if (((tmp_156_fu_1439_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state24))) begin
            RUNcnt_reg_627 <= 32'd1;
        end else if (((tmp_189_reg_1899 == 1'd0) & (1'b1 == ap_CS_fsm_state29))) begin
            RUNcnt_reg_627 <= phitmp2_fu_1532_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_lossless_regular_mod_fu_698_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state27))) begin
        Ra_1_reg_539 <= Ix_reg_1868;
    end else if (((1'b0 == ap_block_state18_on_subcall_done) & (1'b1 == ap_CS_fsm_state18) & (((tmp_156_reg_1875 == 1'd1) & (tmp_189_reg_1899 == 1'd0) & (tmp_reg_1583 == 1'd1)) | ((tmp_156_reg_1875 == 1'd1) & (tmp_174_reg_1884 == 1'd0) & (tmp_reg_1583 == 1'd1))))) begin
        Ra_1_reg_539 <= Ix3_reg_650;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_lossless_regular_mod_fu_698_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        Ra_2_reg_481 <= Ix_1_reg_1716;
    end else if (((grp_lossless_end_of_run_fu_730_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
        Ra_2_reg_481 <= Ix_s_reg_450;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_156_fu_1439_p2 == 1'd1) & (grp_fu_837_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state24))) begin
        Rb_1_reg_686 <= maxx_5_reg_604;
    end else if ((1'b1 == ap_CS_fsm_state31)) begin
        Rb_1_reg_686 <= psl_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_lossless_regular_mod_fu_698_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state27))) begin
        Rb_3_reg_550 <= Rd_reg_1825;
    end else if (((1'b0 == ap_block_state18_on_subcall_done) & (1'b1 == ap_CS_fsm_state18) & (((tmp_156_reg_1875 == 1'd1) & (tmp_189_reg_1899 == 1'd0) & (tmp_reg_1583 == 1'd1)) | ((tmp_156_reg_1875 == 1'd1) & (tmp_174_reg_1884 == 1'd0) & (tmp_reg_1583 == 1'd1))))) begin
        Rb_3_reg_550 <= Rd6_reg_530;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fu_793_p2 == 1'd0) & (tmp_173_fu_1190_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        Rb_4_reg_439 <= maxx_reg_383;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        Rb_4_reg_439 <= psl_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_lossless_regular_mod_fu_698_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        Rb_6_reg_494 <= Rd_1_reg_1610;
    end else if (((grp_lossless_end_of_run_fu_730_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
        Rb_6_reg_494 <= Rd_2_reg_460;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_fu_857_p2 == 1'd1))) begin
        Rc3_reg_580 <= psl_q0;
    end else if (((1'b0 == ap_block_state18_on_subcall_done) & (1'b1 == ap_CS_fsm_state18) & (((tmp_205_fu_1335_p2 == 1'd0) & (tmp_156_reg_1875 == 1'd0) & (tmp_reg_1583 == 1'd1)) | ((tmp_205_fu_1335_p2 == 1'd0) & (tmp_189_reg_1899 == 1'd0) & (tmp_reg_1583 == 1'd1)) | ((tmp_205_fu_1335_p2 == 1'd0) & (tmp_174_reg_1884 == 1'd0) & (tmp_reg_1583 == 1'd1))))) begin
        Rc3_reg_580 <= ap_phi_mux_Rc_2_phi_fu_564_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_fu_857_p2 == 1'd0))) begin
        Rc_1_reg_373 <= psl_q0;
    end else if (((1'b0 == ap_block_state18_on_subcall_done) & (1'b1 == ap_CS_fsm_state18) & (((tmp_207_fu_1319_p2 == 1'd0) & (tmp_193_reg_1747 == 1'd0) & (tmp_reg_1583 == 1'd0)) | ((tmp_207_fu_1319_p2 == 1'd0) & (tmp_183_reg_1732 == 1'd0) & (tmp_reg_1583 == 1'd0)) | ((tmp_207_fu_1319_p2 == 1'd0) & (tmp_173_reg_1723 == 1'd0) & (tmp_reg_1583 == 1'd0))))) begin
        Rc_1_reg_373 <= Rc_3_reg_506;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_lossless_regular_mod_fu_698_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state27))) begin
        Rc_2_reg_561 <= maxx_5_reg_604;
    end else if (((1'b0 == ap_block_state18_on_subcall_done) & (1'b1 == ap_CS_fsm_state18) & (((tmp_156_reg_1875 == 1'd1) & (tmp_189_reg_1899 == 1'd0) & (tmp_reg_1583 == 1'd1)) | ((tmp_156_reg_1875 == 1'd1) & (tmp_174_reg_1884 == 1'd0) & (tmp_reg_1583 == 1'd1))))) begin
        Rc_2_reg_561 <= Rb_1_reg_686;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_lossless_regular_mod_fu_698_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        Rc_3_reg_506 <= maxx_reg_383;
    end else if (((grp_lossless_end_of_run_fu_730_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
        Rc_3_reg_506 <= Rb_4_reg_439;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_156_fu_1439_p2 == 1'd1) & (grp_fu_837_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state24))) begin
        Rd6_reg_530 <= Rd_reg_1825;
    end else if ((1'b1 == ap_CS_fsm_state31)) begin
        Rd6_reg_530 <= psl_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fu_793_p2 == 1'd0) & (tmp_173_fu_1190_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        Rd_2_reg_460 <= Rd_1_reg_1610;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        Rd_2_reg_460 <= psl_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_state36) & (grp_process_run_fu_766_bits_o_ap_vld == 1'b1)) | ((1'b1 == ap_CS_fsm_state19) & (grp_process_run_fu_766_bits_o_ap_vld == 1'b1)) | ((grp_process_run_fu_766_bits_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state33)) | ((grp_process_run_fu_766_bits_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state15)))) begin
        bits <= grp_process_run_fu_766_bits_o;
    end else if ((((1'b1 == ap_CS_fsm_state17) & (grp_lossless_end_of_run_fu_730_bits_o_ap_vld == 1'b1)) | ((ap_predicate_op208_call_state18 == 1'b1) & (grp_lossless_end_of_run_fu_730_bits_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state18)))) begin
        bits <= grp_lossless_end_of_run_fu_730_bits_o;
    end else if ((((1'b1 == ap_CS_fsm_state27) & (grp_lossless_regular_mod_fu_698_bits_o_ap_vld == 1'b1)) | ((1'b1 == ap_CS_fsm_state10) & (grp_lossless_regular_mod_fu_698_bits_o_ap_vld == 1'b1)))) begin
        bits <= grp_lossless_regular_mod_fu_698_bits_o;
    end
end

always @ (posedge ap_clk) begin
    if ((grp_fu_837_p2 == 1'd1)) begin
        if (((tmp_156_fu_1439_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state24))) begin
            i_1_reg_639 <= i_reg_591;
        end else if (((tmp_189_reg_1899 == 1'd0) & (1'b1 == ap_CS_fsm_state29))) begin
            i_1_reg_639 <= i_8_reg_1893;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_156_fu_1439_p2 == 1'd1) & (grp_fu_837_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state24))) begin
        i_2_reg_674 <= i_reg_591;
    end else if ((1'b1 == ap_CS_fsm_state31)) begin
        i_2_reg_674 <= i_8_reg_1893;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_lossless_regular_mod_fu_698_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state27))) begin
        i_3_reg_571 <= i_reg_591;
    end else if (((1'b0 == ap_block_state18_on_subcall_done) & (1'b1 == ap_CS_fsm_state18) & (((tmp_156_reg_1875 == 1'd1) & (tmp_189_reg_1899 == 1'd0) & (tmp_reg_1583 == 1'd1)) | ((tmp_156_reg_1875 == 1'd1) & (tmp_174_reg_1884 == 1'd0) & (tmp_reg_1583 == 1'd1))))) begin
        i_3_reg_571 <= i_2_reg_674;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_fu_857_p2 == 1'd0))) begin
        i_4_reg_361 <= 32'd1;
    end else if (((1'b0 == ap_block_state18_on_subcall_done) & (1'b1 == ap_CS_fsm_state18) & (((tmp_207_fu_1319_p2 == 1'd0) & (tmp_193_reg_1747 == 1'd0) & (tmp_reg_1583 == 1'd0)) | ((tmp_207_fu_1319_p2 == 1'd0) & (tmp_183_reg_1732 == 1'd0) & (tmp_reg_1583 == 1'd0)) | ((tmp_207_fu_1319_p2 == 1'd0) & (tmp_173_reg_1723 == 1'd0) & (tmp_reg_1583 == 1'd0))))) begin
        i_4_reg_361 <= i_11_fu_1313_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((grp_fu_793_p2 == 1'd1)) begin
        if (((tmp_173_fu_1190_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
            i_5_reg_403 <= i_4_reg_361;
        end else if ((1'b1 == ap_CS_fsm_state12)) begin
            i_5_reg_403 <= i_10_reg_1741;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fu_793_p2 == 1'd0) & (tmp_173_fu_1190_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        i_6_reg_470 <= i_4_reg_361;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        i_6_reg_470 <= i_10_reg_1741;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_lossless_regular_mod_fu_698_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        i_7_reg_519 <= i_4_reg_361;
    end else if (((grp_lossless_end_of_run_fu_730_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
        i_7_reg_519 <= i_6_reg_470;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_fu_857_p2 == 1'd1))) begin
        i_reg_591 <= 32'd1;
    end else if (((1'b0 == ap_block_state18_on_subcall_done) & (1'b1 == ap_CS_fsm_state18) & (((tmp_205_fu_1335_p2 == 1'd0) & (tmp_156_reg_1875 == 1'd0) & (tmp_reg_1583 == 1'd1)) | ((tmp_205_fu_1335_p2 == 1'd0) & (tmp_189_reg_1899 == 1'd0) & (tmp_reg_1583 == 1'd1)) | ((tmp_205_fu_1335_p2 == 1'd0) & (tmp_174_reg_1884 == 1'd0) & (tmp_reg_1583 == 1'd1))))) begin
        i_reg_591 <= i_9_fu_1329_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_fu_857_p2 == 1'd1))) begin
        maxx_5_reg_604 <= psl_q1;
    end else if (((1'b0 == ap_block_state18_on_subcall_done) & (1'b1 == ap_CS_fsm_state18) & (((tmp_205_fu_1335_p2 == 1'd0) & (tmp_156_reg_1875 == 1'd0) & (tmp_reg_1583 == 1'd1)) | ((tmp_205_fu_1335_p2 == 1'd0) & (tmp_189_reg_1899 == 1'd0) & (tmp_reg_1583 == 1'd1)) | ((tmp_205_fu_1335_p2 == 1'd0) & (tmp_174_reg_1884 == 1'd0) & (tmp_reg_1583 == 1'd1))))) begin
        maxx_5_reg_604 <= ap_phi_mux_Rb_3_phi_fu_553_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_fu_857_p2 == 1'd0))) begin
        maxx_reg_383 <= psl_q1;
    end else if (((1'b0 == ap_block_state18_on_subcall_done) & (1'b1 == ap_CS_fsm_state18) & (((tmp_207_fu_1319_p2 == 1'd0) & (tmp_193_reg_1747 == 1'd0) & (tmp_reg_1583 == 1'd0)) | ((tmp_207_fu_1319_p2 == 1'd0) & (tmp_183_reg_1732 == 1'd0) & (tmp_reg_1583 == 1'd0)) | ((tmp_207_fu_1319_p2 == 1'd0) & (tmp_173_reg_1723 == 1'd0) & (tmp_reg_1583 == 1'd0))))) begin
        maxx_reg_383 <= Rb_6_reg_494;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_fu_857_p2 == 1'd0))) begin
        minx_5_reg_393 <= sl_q0;
    end else if (((1'b0 == ap_block_state18_on_subcall_done) & (1'b1 == ap_CS_fsm_state18) & (((tmp_207_fu_1319_p2 == 1'd0) & (tmp_193_reg_1747 == 1'd0) & (tmp_reg_1583 == 1'd0)) | ((tmp_207_fu_1319_p2 == 1'd0) & (tmp_183_reg_1732 == 1'd0) & (tmp_reg_1583 == 1'd0)) | ((tmp_207_fu_1319_p2 == 1'd0) & (tmp_173_reg_1723 == 1'd0) & (tmp_reg_1583 == 1'd0))))) begin
        minx_5_reg_393 <= Ra_2_reg_481;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_fu_857_p2 == 1'd1))) begin
        minx_reg_616 <= sl_q0;
    end else if (((1'b0 == ap_block_state18_on_subcall_done) & (1'b1 == ap_CS_fsm_state18) & (((tmp_205_fu_1335_p2 == 1'd0) & (tmp_156_reg_1875 == 1'd0) & (tmp_reg_1583 == 1'd1)) | ((tmp_205_fu_1335_p2 == 1'd0) & (tmp_189_reg_1899 == 1'd0) & (tmp_reg_1583 == 1'd1)) | ((tmp_205_fu_1335_p2 == 1'd0) & (tmp_174_reg_1884 == 1'd0) & (tmp_reg_1583 == 1'd1))))) begin
        minx_reg_616 <= ap_phi_mux_Ra_1_phi_fu_542_p4;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_state36) & (grp_process_run_fu_766_reg_r_o_ap_vld == 1'b1)) | ((1'b1 == ap_CS_fsm_state19) & (grp_process_run_fu_766_reg_r_o_ap_vld == 1'b1)) | ((grp_process_run_fu_766_reg_r_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state33)) | ((grp_process_run_fu_766_reg_r_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state15)))) begin
        reg_r <= grp_process_run_fu_766_reg_r_o;
    end else if ((((1'b1 == ap_CS_fsm_state17) & (grp_lossless_end_of_run_fu_730_reg_r_o_ap_vld == 1'b1)) | ((ap_predicate_op208_call_state18 == 1'b1) & (grp_lossless_end_of_run_fu_730_reg_r_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state18)))) begin
        reg_r <= grp_lossless_end_of_run_fu_730_reg_r_o;
    end else if ((((1'b1 == ap_CS_fsm_state27) & (grp_lossless_regular_mod_fu_698_reg_r_o_ap_vld == 1'b1)) | ((1'b1 == ap_CS_fsm_state10) & (grp_lossless_regular_mod_fu_698_reg_r_o_ap_vld == 1'b1)))) begin
        reg_r <= grp_lossless_regular_mod_fu_698_reg_r_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        Ix_1_reg_1716 <= sl_q0;
        tmp_173_reg_1723 <= tmp_173_fu_1190_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_189_reg_1899 == 1'd0) & (1'b1 == ap_CS_fsm_state29))) begin
        Ix_2_reg_1913 <= sl_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        Ix_3_reg_1761 <= sl_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        Ix_reg_1868 <= sl_q0;
        tmp_156_reg_1875 <= tmp_156_fu_1439_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        Px_1_reg_1888 <= Px_1_fu_1508_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        Px_3_reg_1736 <= Px_3_fu_1261_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        Rd_1_reg_1610 <= psl_q0;
        tmp_166_reg_1627 <= diff_1_fu_882_p2[32'd16];
        tmp_167_reg_1634 <= tmp_167_fu_900_p2;
        tmp_168_reg_1640 <= tmp_168_fu_906_p2;
        tmp_182_cast_reg_1617[15 : 0] <= tmp_182_cast_fu_874_p1[15 : 0];
        tmp_195_cast_reg_1622[15 : 0] <= tmp_195_cast_fu_878_p1[15 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        Rd_reg_1825 <= psl_q1;
        tmp_154_reg_1837 <= tmp_154_fu_1373_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        cont_reg_1862 <= cont_fu_1434_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        i_10_reg_1741 <= i_10_fu_1269_p2;
        tmp_193_reg_1747 <= tmp_193_fu_1275_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        i_8_reg_1893 <= i_8_fu_1516_p2;
        tmp_189_reg_1899 <= tmp_189_fu_1522_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        newSel2_reg_1706 <= newSel2_fu_1119_p3;
        newSel8_reg_1711 <= newSel8_fu_1173_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        newSel5_reg_1673 <= newSel5_fu_1016_p3;
        tmp_160_reg_1650 <= diff_fu_926_p2[32'd16];
        tmp_161_reg_1657 <= tmp_161_fu_943_p2;
        tmp_162_reg_1663 <= tmp_162_fu_949_p2;
        tmp_170_reg_1678 <= diff_2_fu_1028_p2[32'd16];
        tmp_171_reg_1685 <= tmp_171_fu_1045_p2;
        tmp_172_reg_1691 <= tmp_172_fu_1051_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state8))) begin
        reg_843 <= grp_fu_813_p3;
        reg_848[1] <= grp_fu_829_p3[1];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        tmp_152_reg_1820 <= tmp_152_fu_1351_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_156_fu_1439_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state24))) begin
        tmp_174_reg_1884 <= grp_fu_837_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_173_fu_1190_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        tmp_183_reg_1732 <= grp_fu_793_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_189_fu_1522_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state28))) begin
        tmp_194_reg_1903 <= tmp_194_fu_1527_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_193_fu_1275_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        tmp_196_reg_1751 <= tmp_196_fu_1280_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_process_run_fu_766_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state33))) begin
        tmp_202_reg_1946 <= tmp_202_fu_1549_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_process_run_fu_766_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
        tmp_203_reg_1794 <= tmp_203_fu_1302_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_reg_1583 <= tmp_fu_857_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        vLUT_load_1_reg_1847 <= vLUT_q1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | ((ap_predicate_op208_call_state18 == 1'b1) & (1'b1 == ap_CS_fsm_state18)))) begin
        A_address0 = grp_lossless_end_of_run_fu_730_A_address0;
    end else if (((1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state10))) begin
        A_address0 = grp_lossless_regular_mod_fu_698_A_address0;
    end else begin
        A_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | ((ap_predicate_op208_call_state18 == 1'b1) & (1'b1 == ap_CS_fsm_state18)))) begin
        A_ce0 = grp_lossless_end_of_run_fu_730_A_ce0;
    end else if (((1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state10))) begin
        A_ce0 = grp_lossless_regular_mod_fu_698_A_ce0;
    end else begin
        A_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | ((ap_predicate_op208_call_state18 == 1'b1) & (1'b1 == ap_CS_fsm_state18)))) begin
        A_d0 = grp_lossless_end_of_run_fu_730_A_d0;
    end else if (((1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state10))) begin
        A_d0 = grp_lossless_regular_mod_fu_698_A_d0;
    end else begin
        A_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | ((ap_predicate_op208_call_state18 == 1'b1) & (1'b1 == ap_CS_fsm_state18)))) begin
        A_we0 = grp_lossless_end_of_run_fu_730_A_we0;
    end else if (((1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state10))) begin
        A_we0 = grp_lossless_regular_mod_fu_698_A_we0;
    end else begin
        A_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | ((ap_predicate_op208_call_state18 == 1'b1) & (1'b1 == ap_CS_fsm_state18)))) begin
        B_address0 = grp_lossless_end_of_run_fu_730_B_address0;
    end else if (((1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state10))) begin
        B_address0 = grp_lossless_regular_mod_fu_698_B_address0;
    end else begin
        B_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | ((ap_predicate_op208_call_state18 == 1'b1) & (1'b1 == ap_CS_fsm_state18)))) begin
        B_ce0 = grp_lossless_end_of_run_fu_730_B_ce0;
    end else if (((1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state10))) begin
        B_ce0 = grp_lossless_regular_mod_fu_698_B_ce0;
    end else begin
        B_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | ((ap_predicate_op208_call_state18 == 1'b1) & (1'b1 == ap_CS_fsm_state18)))) begin
        B_d0 = grp_lossless_end_of_run_fu_730_B_d0;
    end else if (((1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state10))) begin
        B_d0 = grp_lossless_regular_mod_fu_698_B_d0;
    end else begin
        B_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | ((ap_predicate_op208_call_state18 == 1'b1) & (1'b1 == ap_CS_fsm_state18)))) begin
        B_we0 = grp_lossless_end_of_run_fu_730_B_we0;
    end else if (((1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state10))) begin
        B_we0 = grp_lossless_regular_mod_fu_698_B_we0;
    end else begin
        B_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state10))) begin
        C_ce0 = grp_lossless_regular_mod_fu_698_C_ce0;
    end else begin
        C_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state10))) begin
        C_we0 = grp_lossless_regular_mod_fu_698_C_we0;
    end else begin
        C_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | ((ap_predicate_op208_call_state18 == 1'b1) & (1'b1 == ap_CS_fsm_state18)))) begin
        N_address0 = grp_lossless_end_of_run_fu_730_N_address0;
    end else if (((1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state10))) begin
        N_address0 = grp_lossless_regular_mod_fu_698_N_address0;
    end else begin
        N_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | ((ap_predicate_op208_call_state18 == 1'b1) & (1'b1 == ap_CS_fsm_state18)))) begin
        N_ce0 = grp_lossless_end_of_run_fu_730_N_ce0;
    end else if (((1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state10))) begin
        N_ce0 = grp_lossless_regular_mod_fu_698_N_ce0;
    end else begin
        N_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | ((ap_predicate_op208_call_state18 == 1'b1) & (1'b1 == ap_CS_fsm_state18)))) begin
        N_d0 = grp_lossless_end_of_run_fu_730_N_d0;
    end else if (((1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state10))) begin
        N_d0 = grp_lossless_regular_mod_fu_698_N_d0;
    end else begin
        N_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | ((ap_predicate_op208_call_state18 == 1'b1) & (1'b1 == ap_CS_fsm_state18)))) begin
        N_we0 = grp_lossless_end_of_run_fu_730_N_we0;
    end else if (((1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state10))) begin
        N_we0 = grp_lossless_regular_mod_fu_698_N_we0;
    end else begin
        N_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state18_on_subcall_done) & (1'b1 == ap_CS_fsm_state18) & (((tmp_193_reg_1747 == 1'd1) & (tmp_183_reg_1732 == 1'd1) & (tmp_173_reg_1723 == 1'd1) & (tmp_reg_1583 == 1'd0)) | ((tmp_207_fu_1319_p2 == 1'd1) & (tmp_reg_1583 == 1'd0)) | ((tmp_189_reg_1899 == 1'd1) & (tmp_174_reg_1884 == 1'd1) & (tmp_156_reg_1875 == 1'd1) & (tmp_reg_1583 == 1'd1)) | ((tmp_205_fu_1335_p2 == 1'd1) & (tmp_reg_1583 == 1'd1))))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) & (((tmp_156_reg_1875 == 1'd1) & (tmp_189_reg_1899 == 1'd0) & (tmp_reg_1583 == 1'd1)) | ((tmp_156_reg_1875 == 1'd1) & (tmp_174_reg_1884 == 1'd0) & (tmp_reg_1583 == 1'd1))))) begin
        ap_phi_mux_Ra_1_phi_fu_542_p4 = Ix3_reg_650;
    end else begin
        ap_phi_mux_Ra_1_phi_fu_542_p4 = Ra_1_reg_539;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) & (((tmp_156_reg_1875 == 1'd1) & (tmp_189_reg_1899 == 1'd0) & (tmp_reg_1583 == 1'd1)) | ((tmp_156_reg_1875 == 1'd1) & (tmp_174_reg_1884 == 1'd0) & (tmp_reg_1583 == 1'd1))))) begin
        ap_phi_mux_Rb_3_phi_fu_553_p4 = Rd6_reg_530;
    end else begin
        ap_phi_mux_Rb_3_phi_fu_553_p4 = Rb_3_reg_550;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) & (((tmp_156_reg_1875 == 1'd1) & (tmp_189_reg_1899 == 1'd0) & (tmp_reg_1583 == 1'd1)) | ((tmp_156_reg_1875 == 1'd1) & (tmp_174_reg_1884 == 1'd0) & (tmp_reg_1583 == 1'd1))))) begin
        ap_phi_mux_Rc_2_phi_fu_564_p4 = Rb_1_reg_686;
    end else begin
        ap_phi_mux_Rc_2_phi_fu_564_p4 = Rc_2_reg_561;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) & (((tmp_156_reg_1875 == 1'd1) & (tmp_189_reg_1899 == 1'd0) & (tmp_reg_1583 == 1'd1)) | ((tmp_156_reg_1875 == 1'd1) & (tmp_174_reg_1884 == 1'd0) & (tmp_reg_1583 == 1'd1))))) begin
        ap_phi_mux_i_3_phi_fu_574_p4 = i_2_reg_674;
    end else begin
        ap_phi_mux_i_3_phi_fu_574_p4 = i_3_reg_571;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state18_on_subcall_done) & (1'b1 == ap_CS_fsm_state18) & (((tmp_193_reg_1747 == 1'd1) & (tmp_183_reg_1732 == 1'd1) & (tmp_173_reg_1723 == 1'd1) & (tmp_reg_1583 == 1'd0)) | ((tmp_207_fu_1319_p2 == 1'd1) & (tmp_reg_1583 == 1'd0)) | ((tmp_189_reg_1899 == 1'd1) & (tmp_174_reg_1884 == 1'd1) & (tmp_156_reg_1875 == 1'd1) & (tmp_reg_1583 == 1'd1)) | ((tmp_205_fu_1335_p2 == 1'd1) & (tmp_reg_1583 == 1'd1))))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        classmap_address0 = tmp_179_fu_1444_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        classmap_address0 = tmp_188_fu_1196_p1;
    end else begin
        classmap_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state7))) begin
        classmap_ce0 = 1'b1;
    end else begin
        classmap_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op208_call_state18 == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
        grp_lossless_end_of_run_fu_730_Ix = Ix3_reg_650;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_lossless_end_of_run_fu_730_Ix = Ix_s_reg_450;
    end else begin
        grp_lossless_end_of_run_fu_730_Ix = 'bx;
    end
end

always @ (*) begin
    if (((ap_predicate_op208_call_state18 == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
        grp_lossless_end_of_run_fu_730_RItype = tmp_202_reg_1946;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_lossless_end_of_run_fu_730_RItype = tmp_203_reg_1794;
    end else begin
        grp_lossless_end_of_run_fu_730_RItype = 'bx;
    end
end

always @ (*) begin
    if (((ap_predicate_op208_call_state18 == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
        grp_lossless_end_of_run_fu_730_Ra = minx_reg_616;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_lossless_end_of_run_fu_730_Ra = minx_5_reg_393;
    end else begin
        grp_lossless_end_of_run_fu_730_Ra = 'bx;
    end
end

always @ (*) begin
    if (((ap_predicate_op208_call_state18 == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
        grp_lossless_end_of_run_fu_730_Rb = Rb_1_reg_686;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_lossless_end_of_run_fu_730_Rb = Rb_4_reg_439;
    end else begin
        grp_lossless_end_of_run_fu_730_Rb = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        grp_lossless_regular_mod_fu_698_Px = Px_1_reg_1888;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_lossless_regular_mod_fu_698_Px = Px_3_reg_1736;
    end else begin
        grp_lossless_regular_mod_fu_698_Px = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        grp_lossless_regular_mod_fu_698_xp_read = Ix_reg_1868;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_lossless_regular_mod_fu_698_xp_read = Ix_1_reg_1716;
    end else begin
        grp_lossless_regular_mod_fu_698_xp_read = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state15))) begin
        grp_process_run_fu_766_eoline = 1'd0;
    end else if (((1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state19))) begin
        grp_process_run_fu_766_eoline = 1'd1;
    end else begin
        grp_process_run_fu_766_eoline = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state36)) begin
        grp_process_run_fu_766_runlen = RUNcnt_reg_627;
    end else if ((1'b1 == ap_CS_fsm_state33)) begin
        grp_process_run_fu_766_runlen = RUNcnt_1_reg_661;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_process_run_fu_766_runlen = RUNcnt1_1_reg_426;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        grp_process_run_fu_766_runlen = RUNcnt_2_reg_414;
    end else begin
        grp_process_run_fu_766_runlen = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state36) & (grp_process_run_fu_766_limit_reduce_ap_vld == 1'b1)) | ((1'b1 == ap_CS_fsm_state19) & (grp_process_run_fu_766_limit_reduce_ap_vld == 1'b1)) | ((grp_process_run_fu_766_limit_reduce_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state33)) | ((grp_process_run_fu_766_limit_reduce_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state15)))) begin
        limit_reduce_o = grp_process_run_fu_766_limit_reduce;
    end else begin
        limit_reduce_o = limit_reduce_i;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state15))) begin
        limit_reduce_o_ap_vld = grp_process_run_fu_766_limit_reduce_ap_vld;
    end else begin
        limit_reduce_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        psl_address0 = tmp_199_fu_1544_p1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        psl_address0 = tmp_196_reg_1751;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        psl_address0 = tmp_159_fu_869_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        psl_address0 = 64'd0;
    end else begin
        psl_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        psl_address1 = tmp_194_reg_1903;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        psl_address1 = tmp_148_fu_1346_p1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        psl_address1 = tmp_201_fu_1297_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        psl_address1 = 64'd1;
    end else begin
        psl_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state3) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        psl_ce0 = 1'b1;
    end else begin
        psl_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state12) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        psl_ce1 = 1'b1;
    end else begin
        psl_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        sl_address0 = tmp_194_fu_1527_p1;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        sl_address0 = tmp_s_fu_1423_p1;
    end else if (((1'b1 == ap_CS_fsm_state18) & (((tmp_156_reg_1875 == 1'd0) & (tmp_reg_1583 == 1'd1)) | ((tmp_189_reg_1899 == 1'd0) & (tmp_reg_1583 == 1'd1)) | ((tmp_174_reg_1884 == 1'd0) & (tmp_reg_1583 == 1'd1))))) begin
        sl_address0 = tmp_204_fu_1324_p1;
    end else if (((1'b1 == ap_CS_fsm_state18) & (((tmp_193_reg_1747 == 1'd0) & (tmp_reg_1583 == 1'd0)) | ((tmp_183_reg_1732 == 1'd0) & (tmp_reg_1583 == 1'd0)) | ((tmp_173_reg_1723 == 1'd0) & (tmp_reg_1583 == 1'd0))))) begin
        sl_address0 = tmp_206_fu_1308_p1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        sl_address0 = tmp_196_fu_1280_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        sl_address0 = tmp_157_fu_1068_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        sl_address0 = 64'd0;
    end else begin
        sl_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state6) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state18_on_subcall_done) & (1'b1 == ap_CS_fsm_state18) & (((tmp_156_reg_1875 == 1'd0) & (tmp_reg_1583 == 1'd1)) | ((tmp_189_reg_1899 == 1'd0) & (tmp_reg_1583 == 1'd1)) | ((tmp_174_reg_1884 == 1'd0) & (tmp_reg_1583 == 1'd1)))) | ((1'b0 == ap_block_state18_on_subcall_done) & (1'b1 == ap_CS_fsm_state18) & (((tmp_193_reg_1747 == 1'd0) & (tmp_reg_1583 == 1'd0)) | ((tmp_183_reg_1732 == 1'd0) & (tmp_reg_1583 == 1'd0)) | ((tmp_173_reg_1723 == 1'd0) & (tmp_reg_1583 == 1'd0)))))) begin
        sl_ce0 = 1'b1;
    end else begin
        sl_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        if ((1'b1 == ap_condition_348)) begin
            sl_d0 = ap_phi_mux_Ra_1_phi_fu_542_p4;
        end else if ((1'b1 == ap_condition_339)) begin
            sl_d0 = Ra_2_reg_481;
        end else begin
            sl_d0 = 'bx;
        end
    end else begin
        sl_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state18_on_subcall_done) & (1'b1 == ap_CS_fsm_state18) & (((tmp_156_reg_1875 == 1'd0) & (tmp_reg_1583 == 1'd1)) | ((tmp_189_reg_1899 == 1'd0) & (tmp_reg_1583 == 1'd1)) | ((tmp_174_reg_1884 == 1'd0) & (tmp_reg_1583 == 1'd1)))) | ((1'b0 == ap_block_state18_on_subcall_done) & (1'b1 == ap_CS_fsm_state18) & (((tmp_193_reg_1747 == 1'd0) & (tmp_reg_1583 == 1'd0)) | ((tmp_183_reg_1732 == 1'd0) & (tmp_reg_1583 == 1'd0)) | ((tmp_173_reg_1723 == 1'd0) & (tmp_reg_1583 == 1'd0)))))) begin
        sl_we0 = 1'b1;
    end else begin
        sl_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        vLUT_address0 = tmp_151_fu_1402_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        vLUT_address0 = tmp_164_fu_965_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        vLUT_address0 = tmp_25_cast_fu_918_p1;
    end else begin
        vLUT_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        vLUT_address1 = tmp_24_cast_fu_1418_p1;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        vLUT_address1 = tmp_22_cast_fu_1368_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        vLUT_address1 = tmp_26_cast_fu_1063_p1;
    end else begin
        vLUT_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        vLUT_ce0 = 1'b1;
    end else begin
        vLUT_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state5))) begin
        vLUT_ce1 = 1'b1;
    end else begin
        vLUT_ce1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (tmp_fu_857_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((grp_fu_793_p2 == 1'd1) & (tmp_173_fu_1190_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else if (((grp_fu_793_p2 == 1'd0) & (tmp_173_fu_1190_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((grp_lossless_regular_mod_fu_698_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            if (((tmp_193_fu_1275_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state12 : begin
            if (((grp_fu_793_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            if (((grp_process_run_fu_766_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            if (((grp_lossless_end_of_run_fu_730_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state18 : begin
            if (((1'b0 == ap_block_state18_on_subcall_done) & (1'b1 == ap_CS_fsm_state18) & (((tmp_193_reg_1747 == 1'd1) & (tmp_183_reg_1732 == 1'd1) & (tmp_173_reg_1723 == 1'd1) & (tmp_reg_1583 == 1'd0)) | ((tmp_207_fu_1319_p2 == 1'd1) & (tmp_reg_1583 == 1'd0)) | ((tmp_189_reg_1899 == 1'd1) & (tmp_174_reg_1884 == 1'd1) & (tmp_156_reg_1875 == 1'd1) & (tmp_reg_1583 == 1'd1)) | ((tmp_205_fu_1335_p2 == 1'd1) & (tmp_reg_1583 == 1'd1))))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((1'b0 == ap_block_state18_on_subcall_done) & (1'b1 == ap_CS_fsm_state18) & (((tmp_205_fu_1335_p2 == 1'd0) & (tmp_156_reg_1875 == 1'd0) & (tmp_reg_1583 == 1'd1)) | ((tmp_205_fu_1335_p2 == 1'd0) & (tmp_189_reg_1899 == 1'd0) & (tmp_reg_1583 == 1'd1)) | ((tmp_205_fu_1335_p2 == 1'd0) & (tmp_174_reg_1884 == 1'd0) & (tmp_reg_1583 == 1'd1))))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else if (((1'b0 == ap_block_state18_on_subcall_done) & (1'b1 == ap_CS_fsm_state18) & (((tmp_207_fu_1319_p2 == 1'd0) & (tmp_193_reg_1747 == 1'd0) & (tmp_reg_1583 == 1'd0)) | ((tmp_207_fu_1319_p2 == 1'd0) & (tmp_183_reg_1732 == 1'd0) & (tmp_reg_1583 == 1'd0)) | ((tmp_207_fu_1319_p2 == 1'd0) & (tmp_173_reg_1723 == 1'd0) & (tmp_reg_1583 == 1'd0))))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        ap_ST_fsm_state19 : begin
            if (((grp_process_run_fu_766_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            if (((grp_fu_837_p2 == 1'd1) & (tmp_156_fu_1439_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state24))) begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end else if (((tmp_156_fu_1439_p2 == 1'd1) & (grp_fu_837_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state24))) begin
                ap_NS_fsm = ap_ST_fsm_state32;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            if (((grp_lossless_regular_mod_fu_698_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state27))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state27;
            end
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            if (((grp_fu_837_p2 == 1'd1) & (tmp_189_reg_1899 == 1'd0) & (1'b1 == ap_CS_fsm_state29))) begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end else if (((tmp_189_reg_1899 == 1'd1) & (1'b1 == ap_CS_fsm_state29))) begin
                ap_NS_fsm = ap_ST_fsm_state35;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state30;
            end
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            if (((grp_process_run_fu_766_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state33))) begin
                ap_NS_fsm = ap_ST_fsm_state34;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state33;
            end
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            if (((grp_process_run_fu_766_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state36))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state36;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign C_address0 = grp_lossless_regular_mod_fu_698_C_address0;

assign C_d0 = grp_lossless_regular_mod_fu_698_C_d0;

assign Px_10_fu_1454_p3 = ((tmp_175_fu_1448_p2[0:0] === 1'b1) ? maxx_5_reg_604 : minx_reg_616);

assign Px_11_fu_1462_p3 = ((tmp_175_fu_1448_p2[0:0] === 1'b1) ? minx_reg_616 : maxx_5_reg_604);

assign Px_12_fu_1207_p3 = ((tmp_184_fu_1201_p2[0:0] === 1'b1) ? minx_5_reg_393 : maxx_reg_383);

assign Px_13_fu_1215_p3 = ((tmp_184_fu_1201_p2[0:0] === 1'b1) ? maxx_reg_383 : minx_5_reg_393);

assign Px_1_fu_1508_p3 = ((tmp_176_fu_1470_p2[0:0] === 1'b1) ? Px_6_fu_1500_p3 : Px_11_fu_1462_p3);

assign Px_3_fu_1261_p3 = ((tmp_185_fu_1223_p2[0:0] === 1'b1) ? Px_9_fu_1253_p3 : Px_12_fu_1207_p3);

assign Px_5_fu_1241_p2 = (tmp_187_fu_1235_p2 + minx_5_reg_393);

assign Px_6_fu_1500_p3 = ((sel_tmp_fu_1494_p2[0:0] === 1'b1) ? Px_fu_1488_p2 : Px_10_fu_1454_p3);

assign Px_9_fu_1253_p3 = ((sel_tmp16_fu_1247_p2[0:0] === 1'b1) ? Px_5_fu_1241_p2 : Px_13_fu_1215_p3);

assign Px_fu_1488_p2 = (tmp_178_fu_1482_p2 + minx_reg_616);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd31];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_state34 = ap_CS_fsm[32'd33];

assign ap_CS_fsm_state35 = ap_CS_fsm[32'd34];

assign ap_CS_fsm_state36 = ap_CS_fsm[32'd35];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state18_on_subcall_done = ((ap_predicate_op208_call_state18 == 1'b1) & (grp_lossless_end_of_run_fu_730_ap_done == 1'b0));
end

always @ (*) begin
    ap_condition_339 = (((tmp_193_reg_1747 == 1'd0) & (tmp_reg_1583 == 1'd0)) | ((tmp_183_reg_1732 == 1'd0) & (tmp_reg_1583 == 1'd0)) | ((tmp_173_reg_1723 == 1'd0) & (tmp_reg_1583 == 1'd0)));
end

always @ (*) begin
    ap_condition_348 = (((tmp_156_reg_1875 == 1'd0) & (tmp_reg_1583 == 1'd1)) | ((tmp_189_reg_1899 == 1'd0) & (tmp_reg_1583 == 1'd1)) | ((tmp_174_reg_1884 == 1'd0) & (tmp_reg_1583 == 1'd1)));
end

always @ (*) begin
    ap_predicate_op208_call_state18 = (((tmp_156_reg_1875 == 1'd1) & (tmp_189_reg_1899 == 1'd0) & (tmp_reg_1583 == 1'd1)) | ((tmp_156_reg_1875 == 1'd1) & (tmp_174_reg_1884 == 1'd0) & (tmp_reg_1583 == 1'd1)));
end

assign cont_1_fu_1185_p2 = (tmp5_fu_1181_p2 + newSel5_reg_1673);

assign cont_fu_1434_p2 = (tmp4_fu_1428_p2 + vLUT_load_1_reg_1847);

assign diff_1_fu_882_p2 = (tmp_182_cast_fu_874_p1 - tmp_195_cast_fu_878_p1);

assign diff_2_fu_1028_p2 = (tmp_195_cast_reg_1622 - tmp_212_cast_fu_1024_p1);

assign diff_cast_fu_931_p1 = diff_fu_926_p2;

assign diff_fu_926_p2 = (tmp_181_cast_fu_923_p1 - tmp_182_cast_reg_1617);

assign grp_fu_793_p2 = ((sl_q0 == minx_5_reg_393) ? 1'b1 : 1'b0);

assign grp_fu_799_p3 = classmap_q0[32'd31];

assign grp_fu_807_p2 = (32'd0 - classmap_q0);

assign grp_fu_813_p3 = ((grp_fu_799_p3[0:0] === 1'b1) ? grp_fu_807_p2 : classmap_q0);

assign grp_fu_821_p3 = classmap_q0[32'd31];

assign grp_fu_829_p3 = ((grp_fu_821_p3[0:0] === 1'b1) ? 2'd3 : 2'd1);

assign grp_fu_837_p2 = ((sl_q0 == minx_reg_616) ? 1'b1 : 1'b0);

assign grp_lossless_end_of_run_fu_730_ap_start = grp_lossless_end_of_run_fu_730_ap_start_reg;

assign grp_lossless_regular_mod_fu_698_ap_start = grp_lossless_regular_mod_fu_698_ap_start_reg;

assign grp_process_run_fu_766_ap_start = grp_process_run_fu_766_ap_start_reg;

assign i_10_fu_1269_p2 = (i_5_reg_403 + 32'd1);

assign i_11_fu_1313_p2 = ($signed(i_7_reg_519) + $signed(32'd1));

assign i_8_fu_1516_p2 = (i_1_reg_639 + 32'd1);

assign i_9_fu_1329_p2 = ($signed(ap_phi_mux_i_3_phi_fu_574_p4) + $signed(32'd1));

assign newSel1_fu_1111_p3 = ((sel_tmp4_fu_1073_p2[0:0] === 1'b1) ? vLUT_q0 : 32'd648);

assign newSel2_fu_1119_p3 = ((or_cond_fu_1105_p2[0:0] === 1'b1) ? newSel_fu_1097_p3 : newSel1_fu_1111_p3);

assign newSel3_fu_994_p3 = ((sel_tmp10_fu_989_p2[0:0] === 1'b1) ? 32'd63 : vLUT_q0);

assign newSel4_fu_1008_p3 = ((sel_tmp3_fu_970_p2[0:0] === 1'b1) ? vLUT_q0 : 32'd72);

assign newSel5_fu_1016_p3 = ((or_cond1_fu_1002_p2[0:0] === 1'b1) ? newSel3_fu_994_p3 : newSel4_fu_1008_p3);

assign newSel6_fu_1151_p3 = ((sel_tmp15_fu_1146_p2[0:0] === 1'b1) ? 32'd7 : vLUT_q1);

assign newSel7_fu_1165_p3 = ((sel_tmp11_fu_1127_p2[0:0] === 1'b1) ? vLUT_q1 : 32'd8);

assign newSel8_fu_1173_p3 = ((or_cond2_fu_1159_p2[0:0] === 1'b1) ? newSel6_fu_1151_p3 : newSel7_fu_1165_p3);

assign newSel_fu_1097_p3 = ((sel_tmp2_fu_1092_p2[0:0] === 1'b1) ? 32'd567 : vLUT_q0);

assign or_cond1_fu_1002_p2 = (sel_tmp8_fu_979_p2 | sel_tmp10_fu_989_p2);

assign or_cond2_fu_1159_p2 = (sel_tmp15_fu_1146_p2 | sel_tmp13_fu_1136_p2);

assign or_cond_fu_1105_p2 = (sel_tmp7_fu_1082_p2 | sel_tmp2_fu_1092_p2);

assign phitmp2_fu_1532_p2 = (RUNcnt_reg_627 + 32'd1);

assign phitmp_fu_1285_p2 = (RUNcnt_2_reg_414 + 32'd1);

assign sel_tmp10_fu_989_p2 = (tmp_166_reg_1627 & sel_tmp1_fu_984_p2);

assign sel_tmp11_fu_1127_p2 = (tmp_171_reg_1685 & tmp_170_reg_1678);

assign sel_tmp12_fu_1131_p2 = (tmp_170_reg_1678 ^ 1'd1);

assign sel_tmp13_fu_1136_p2 = (tmp_172_reg_1691 & sel_tmp12_fu_1131_p2);

assign sel_tmp14_fu_1141_p2 = (tmp_171_reg_1685 ^ 1'd1);

assign sel_tmp15_fu_1146_p2 = (tmp_170_reg_1678 & sel_tmp14_fu_1141_p2);

assign sel_tmp16_fu_1247_p2 = (tmp_186_fu_1229_p2 & tmp_185_fu_1223_p2);

assign sel_tmp1_fu_984_p2 = (tmp_167_reg_1634 ^ 1'd1);

assign sel_tmp2_fu_1092_p2 = (tmp_160_reg_1650 & sel_tmp9_fu_1087_p2);

assign sel_tmp3_fu_970_p2 = (tmp_167_reg_1634 & tmp_166_reg_1627);

assign sel_tmp4_fu_1073_p2 = (tmp_161_reg_1657 & tmp_160_reg_1650);

assign sel_tmp5_fu_974_p2 = (tmp_166_reg_1627 ^ 1'd1);

assign sel_tmp6_fu_1077_p2 = (tmp_160_reg_1650 ^ 1'd1);

assign sel_tmp7_fu_1082_p2 = (tmp_162_reg_1663 & sel_tmp6_fu_1077_p2);

assign sel_tmp8_fu_979_p2 = (tmp_168_reg_1640 & sel_tmp5_fu_974_p2);

assign sel_tmp9_fu_1087_p2 = (tmp_161_reg_1657 ^ 1'd1);

assign sel_tmp_fu_1494_p2 = (tmp_177_fu_1476_p2 & tmp_176_fu_1470_p2);

assign tmp4_fu_1428_p2 = (vLUT_q0 + vLUT_q1);

assign tmp5_fu_1181_p2 = (newSel2_reg_1706 + newSel8_reg_1711);

assign tmp_147_fu_1340_p2 = ($signed(i_reg_591) + $signed(32'd1));

assign tmp_148_fu_1346_p1 = $signed(tmp_147_fu_1340_p2);

assign tmp_149_fu_1386_p2 = (17'd256 - tmp_164_cast_fu_1382_p1);

assign tmp_150_fu_1396_p2 = ($signed(tmp_165_cast_fu_1392_p1) + $signed(tmp_163_cast_fu_1379_p1));

assign tmp_151_fu_1402_p1 = $signed(tmp_150_fu_1396_p2);

assign tmp_152_fu_1351_p2 = (16'd256 - Rc3_reg_580);

assign tmp_153_fu_1357_p2 = (tmp_152_reg_1820 + maxx_5_reg_604);

assign tmp_154_fu_1373_p2 = (Rc3_reg_580 + 16'd256);

assign tmp_155_fu_1407_p2 = (tmp_154_reg_1837 - minx_reg_616);

assign tmp_156_fu_1439_p2 = ((cont_reg_1862 == 32'd0) ? 1'b1 : 1'b0);

assign tmp_157_fu_1068_p1 = i_4_reg_361;

assign tmp_158_fu_863_p2 = ($signed(32'd1) + $signed(i_4_reg_361));

assign tmp_159_fu_869_p1 = $signed(tmp_158_fu_863_p2);

assign tmp_161_fu_943_p2 = (($signed(diff_fu_926_p2) > $signed(17'd126571)) ? 1'b1 : 1'b0);

assign tmp_162_fu_949_p2 = (($signed(diff_fu_926_p2) < $signed(17'd4501)) ? 1'b1 : 1'b0);

assign tmp_163_cast_fu_1379_p1 = Rd_reg_1825;

assign tmp_163_fu_955_p2 = ($signed(18'd4501) + $signed(diff_cast_fu_931_p1));

assign tmp_164_cast_fu_1382_p1 = maxx_5_reg_604;

assign tmp_164_fu_965_p1 = $unsigned(tmp_191_cast_fu_961_p1);

assign tmp_165_cast_fu_1392_p1 = $signed(tmp_149_fu_1386_p2);

assign tmp_165_fu_888_p1 = diff_1_fu_882_p2[15:0];

assign tmp_167_fu_900_p2 = (($signed(diff_1_fu_882_p2) > $signed(17'd126571)) ? 1'b1 : 1'b0);

assign tmp_168_fu_906_p2 = (($signed(diff_1_fu_882_p2) < $signed(17'd4501)) ? 1'b1 : 1'b0);

assign tmp_169_fu_1033_p1 = diff_2_fu_1028_p2[15:0];

assign tmp_171_fu_1045_p2 = (($signed(diff_2_fu_1028_p2) > $signed(17'd126571)) ? 1'b1 : 1'b0);

assign tmp_172_fu_1051_p2 = (($signed(diff_2_fu_1028_p2) < $signed(17'd4501)) ? 1'b1 : 1'b0);

assign tmp_173_fu_1190_p2 = ((cont_1_fu_1185_p2 == 32'd0) ? 1'b1 : 1'b0);

assign tmp_175_fu_1448_p2 = ((maxx_5_reg_604 > minx_reg_616) ? 1'b1 : 1'b0);

assign tmp_176_fu_1470_p2 = ((Rc3_reg_580 < Px_10_fu_1454_p3) ? 1'b1 : 1'b0);

assign tmp_177_fu_1476_p2 = ((Rc3_reg_580 > Px_11_fu_1462_p3) ? 1'b1 : 1'b0);

assign tmp_178_fu_1482_p2 = (maxx_5_reg_604 - Rc3_reg_580);

assign tmp_179_fu_1444_p1 = cont_reg_1862;

assign tmp_181_cast_fu_923_p1 = Rd_1_reg_1610;

assign tmp_182_cast_fu_874_p1 = maxx_reg_383;

assign tmp_184_fu_1201_p2 = ((maxx_reg_383 > minx_5_reg_393) ? 1'b1 : 1'b0);

assign tmp_185_fu_1223_p2 = ((Rc_1_reg_373 < Px_13_fu_1215_p3) ? 1'b1 : 1'b0);

assign tmp_186_fu_1229_p2 = ((Rc_1_reg_373 > Px_12_fu_1207_p3) ? 1'b1 : 1'b0);

assign tmp_187_fu_1235_p2 = (maxx_reg_383 - Rc_1_reg_373);

assign tmp_188_fu_1196_p1 = cont_1_fu_1185_p2;

assign tmp_189_fu_1522_p2 = (($signed(i_8_fu_1516_p2) > $signed(no)) ? 1'b1 : 1'b0);

assign tmp_191_cast_fu_961_p1 = $signed(tmp_163_fu_955_p2);

assign tmp_193_fu_1275_p2 = (($signed(i_10_fu_1269_p2) > $signed(no)) ? 1'b1 : 1'b0);

assign tmp_194_fu_1527_p1 = i_8_fu_1516_p2;

assign tmp_195_cast_fu_878_p1 = Rc_1_reg_373;

assign tmp_196_fu_1280_p1 = i_10_fu_1269_p2;

assign tmp_198_fu_1538_p2 = (i_1_reg_639 + 32'd2);

assign tmp_199_fu_1544_p1 = $signed(tmp_198_fu_1538_p2);

assign tmp_200_fu_1291_p2 = (i_5_reg_403 + 32'd2);

assign tmp_201_fu_1297_p1 = $signed(tmp_200_fu_1291_p2);

assign tmp_202_fu_1549_p2 = ((minx_reg_616 == Rb_1_reg_686) ? 1'b1 : 1'b0);

assign tmp_203_fu_1302_p2 = ((minx_5_reg_393 == Rb_4_reg_439) ? 1'b1 : 1'b0);

assign tmp_204_fu_1324_p1 = ap_phi_mux_i_3_phi_fu_574_p4;

assign tmp_205_fu_1335_p2 = (($signed(i_9_fu_1329_p2) > $signed(no)) ? 1'b1 : 1'b0);

assign tmp_206_fu_1308_p1 = i_7_reg_519;

assign tmp_207_fu_1319_p2 = (($signed(i_11_fu_1313_p2) > $signed(no)) ? 1'b1 : 1'b0);

assign tmp_212_cast_fu_1024_p1 = minx_5_reg_393;

assign tmp_22_cast_fu_1368_p1 = $signed(tmp_22_fu_1362_p2);

assign tmp_22_fu_1362_p2 = (tmp_153_fu_1357_p2 + 16'd9002);

assign tmp_24_cast_fu_1418_p1 = $signed(tmp_24_fu_1412_p2);

assign tmp_24_fu_1412_p2 = (tmp_155_fu_1407_p2 + 16'd18004);

assign tmp_25_cast_fu_918_p1 = $signed(tmp_25_fu_912_p2);

assign tmp_25_fu_912_p2 = (16'd13503 + tmp_165_fu_888_p1);

assign tmp_26_cast_fu_1063_p1 = $signed(tmp_26_fu_1057_p2);

assign tmp_26_fu_1057_p2 = (16'd22505 + tmp_169_fu_1033_p1);

assign tmp_fu_857_p2 = ((bpp16 == 32'd0) ? 1'b1 : 1'b0);

assign tmp_s_fu_1423_p1 = i_reg_591;

always @ (posedge ap_clk) begin
    reg_848[0] <= 1'b1;
    tmp_182_cast_reg_1617[16] <= 1'b0;
    tmp_195_cast_reg_1622[16] <= 1'b0;
end

endmodule //lossless_doscanline
